#!/bin/bash
# vim: set ft=sh

set -e

cd concourse

# check if smoke tests already downloaded fly
if ! [ -e /usr/local/bin/fly ]; then
  go install ./fly
fi

cd web/wats

yarn install
yarn test -v --color "$@"
